global:
  scrape_interval: 1m
  scrape_timeout: 10s
scrape_configs:
  - job_name: waterstream-kafka
    sample_limit: 10000
    file_sd_configs:
      - files: [ "/tmp/cwagent_ecs_auto_sd.yaml" ]
  - job_name: kafka-broker
    file_sd_configs:
      - files: [ "/etc/prometheus/kafka_targets.json" ]
